name: kmat_tools
channels:
  - camiladuitama
  - tlemane
  - auto
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - kmtricks
  - libgcc-ng >=13
  - ca-certificates
  - colorama
  - kmat_tools
  - pip
  - python
  - setuptools
  - wheel
  - zlib
