{% set name = "kmat_tools" %}
{% set version = "0.0.18" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/kmat_tools-{{ version }}.tar.gz
  sha256: 9ff0ab395e2ddedb3b45c745e0a9861959f2806d053650a6d5531a4680110fa6

build:
  entry_points:
    - kmat_tools = kmat_tools.__main__:main
    - km_basic_filter = cython_helpers.km_tools_wrappers.km_basic_filter_wrapper:km_basic_filter_main
    - km_fasta = cython_helpers.km_tools_wrappers.km_fasta_wrapper:km_fasta_main
    - km_unitig = cython_helpers.km_tools_wrappers.km_unitig_wrapper:km_unitig_main
  script: python setup.py build_ext --inplace
  number: 0

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - python
    - setuptools
    - wheel
    - Cython
    - colorama
    - pip
  run:
    - python
    - colorama
    - Cython
    - wheel
    - setuptools

test:
  imports:
    - cython_helpers
    - kmat_tools
  commands:
    - pip check
    - kmat_tools --help
    - km_basic_filter --help
    - km_fasta --help
    - km_unitig --help
  requires:
    - pip

about:
  home: https://github.com/CamilaDuitama/kmat_tools
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - camiladuitama
