package:
  name: kmat_tools
  version: "0.2.0"

source:
  path: ../ 
  include:  
    - README.md
    - LICENSE
    - src/**
    - include/**
    - external/**
    - test/**
    - CMakeLists.txt
    - scripts/**
    - MANIFEST.in 

build:
  number: 0
  string: "h{{ PKG_BUILDNUM }}"
  ignore_run_exports:
   - python
   - zlib


requirements:
  build:
    - {{ compiler('cxx') }}
    - cmake >=3.15
    - make
    - cython
    - python >=3.12
    - setuptools
    - zlib
    - pthread-stubs #Optional

  host:
    - setuptools
    - cython
    - python >=3.12
    - zlib
  run:
    - python
    - colorama
    - python >=3.12
    - zlib  # specify runtime dependencies if any

about:
  home: "https://github.com/CamilaDuitama/kmat_tools"
  license: MIT
  summary: "Python package for creating unitig matrix from fof.txt file and set of FASTA/FASTQ files using kmat_tools"
  description: |
    `kmat_tools` is a tool for creating unitig matrix from fof.txt file and set of FASTA/FASTQ files.
  dev_url: "https://github.com/CamilaDuitama/kmat_tools"

extra:
  recipe-maintainers:
    - CamilaDuitama

test:
  files:
    - test/fof.txt
    - test/D1.fastq
    - test/D2.fastq
    - test/D3.fastq
    - test/D4.fastq
    - test/D5.fastq
    - test/D6.fastq
    - test/D7.fastq
    - test/D8.fastq
    - test/D9.fastq
    - test/D10.fastq 

  commands:
    - test -f $PREFIX/bin/kmtools
    - kmtools --version
